/*
 * Problem it Solves: Generates Pythagorean Triplets (a, b, c) s.t. a^2 + b^2 = c^2.
 * Usage: Standard precomputation.
 * Input/Output: N -> list of triplets.
 * Time Complexity: O(N).
 * Tweaks: Euclid's formula: a = m^2 - n^2, b = 2mn, c = m^2 + n^2.
 * Other Use Cases: Geometry problems.
 * Warnings: Generates primitive triples; multiples can be generated by k.
 */

#include <bits/stdc++.h>
using namespace std;

const int N = 1e6 + 9;

vector<pair<int, int>> ans[N]; //ans[c] = {{a, b}}, s.t. a^2 + b^2 = c^2

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    int cnt = 0;
    for (int m = 1; m * m < N; m++) {
        for (int n = 1; n < m; n++) {
            if ((n & 1) == (m & 1)) continue;
            int a = m * m - n * n, b = 2 * m * n, c = m * m + n * n;
            if (__gcd(a, b) > 1) continue;
            for (int k = 1; k * c < N; k++) { // use only k = 1 to generate only primitive triples 
                ans[c * k].emplace_back(a * k, b * k);
                cnt++;
            }
        }
    }
    for (int i = 1; i <= 1000; i++) {
        for (auto x : ans[i]) cout << x.first << ' ' << x.second << ' ' << i << '\n';
    }
    return 0;
}
